pc_ip: "192.168.1.108"
pc_port: 8888
inventory_path: "/namazu/inventory.xml"
csv_save_path: "/namazu/"
csv_states: ['2', '3']
buffer_size_ms: 3000
richter_b: 0.0
richter_threshold: 4.0
pre_filt: [0.01, 0.02, 20.0, 50.0]
state_ranges:
  state_0: [0, 3.0]
  state_1: [3.0, 4.0]
  state_2: [4.0, 5.0]
  state_3: [5.0, 10.0]
network: "AM"
station: "R8C49"
location: "00"
channel: "EHZ"
sampling_rate: 100.0
emitter_baud_rate: 9600
emitter_serial_port: "/dev/ttyACM0"
tx_gpio_pin: 26
baud_rate: 9600
